---

- name: Add mongoDB repo key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: EA312927
  tags: install

- name: Add mongodb repository
  apt_repository:
    repo: "{{ mongo_repo }}"
  tags: install

- name: Install mongodb packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - "{{ mongo_packages }}"
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
