---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: db-role-travis
    image: ubuntu-1604-xenial-v20180627
    machine_type: f1-micro
    zone: europe-west1-b
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
